name: Duplicate Symlinks

on:
  push

jobs:
  duplicate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Duplicate Symlinks
        run: |
          ln -s $(pwd)/proprietary-content-cms-live/locals.tf $(pwd)/make-wow/
