name: Duplicate Symlinks

on:
  push
  
jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Print current directory
        run: |
          pwd

      
      - name: Copy locals.tf
        run: |
          cp proprietary-content-cms-live/locals.tf make-wow
