name: Move Symlinks

on:
  workflow_dispatch:
    inputs:
      source_folder:
        description: 'Source Folder'
        default: proprietary-content-cms-live
        required: true
      destination_folder:
        description: 'Destination Folder'
        required: true
        default: make-wow
      
        
jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Print current directory
        run: |
          pwd
      - name: List contents of mmm directory (using ls -l)
        run: |
          ls
      
      - name: Copy locals.tf
        run: |
          cp -P ${{github.event.inputs.source_folder}}/locals.tf ${{github.event.inputs.destination_folder}}
          
      - name: Commit changes
        run: |
          github_status = $(git status --short) 
          cat github_status
          if n=${#github_status} > 0:
            git config --global user.email "Mirza_Baig@epam.com"
            git config --global user.name "omar123mok"
            git add -A
            git commit -m "Update symlinks"
            git push
