name: Move Symlinks

on:
  workflow_dispatch:
    inputs:
      trigger:
        description: 'Trigger the workflow via Lambda'
        required: true
        default: ''
jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Print current directory
        run: |
          pwd
      - name: List contents of mmm directory (using ls -l)
        run: |
          ls
      
      - name: Copy locals.tf
        run: |
          cp -P make-wow/locals.tf proprietary-content-cms-live
          
      - name: Commit changes
        run: |
          git config --global user.email "Mirza_Baig@epam.com"
          git config --global user.name "omar123mok"
          git add -A
          git commit -m "Update symlinks"
          git push

